id: P003102
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03
  title: སྤྱོད་འཇུག་གི་འགྲེལ་པ།
  author: ''
  volumes:
    aa2146fc8f2e497daff8e1339403032d:
      image_group_id: I1KG10609
      title: ''
      volume_number: 1
      total_pages: 149
